---
platform: linux

inputs:
  - name: dev-ci

# You can cache parts of the project for reuse.
# For example, if running a front-end application that used npm,
# you can use the below sample snippet to cache your node_modules directory

#caches:
#  - path: dev-ci/node_modules

run:
  path: dev-ci/sample-pipeline/tasks/unit-test/run.sh