---
platform: linux

inputs:
  - name: dev-git-project
  - name: ci

# You can cache parts of the project for reuse.
# For example, if running a front-end application that used npm,
# you can use the below sample snippet to cache your node_modules directory

#caches:
#  - path: dev-git-project/node_modules

run:
  path: ci/sample-pipeline/tasks/unit-test/run.sh